console.log(Math.abs(-5))
console.log(Math.ceil(4.3))
console.log(Math.floor(4.9))
console.log(Math.max(3,7,2,9,5))
console.log(Math.min(3,7,2,9,5))
console.log(Math.pow(2,3))
console.log(Math.sqrt(25))
console.log(Math.random())
console.log(Math.floor(Math.random()*10)+1)

